title:              Speckhofer Enterprises
# email:              your-email@example.com
description:        A website by Thomas Speckhofer
author:             Thomas Speckhofer
baseurl:            ""
url:                "https://tspeckhofer.github.io"

# Social Profiles
# twitter_username:   SBootstrap
github_username:    tspeckhofer
# facebook_username:  StartBootstrap
# instagram_username:  
# linkedin_username:

# Add your google-analytics ID here to activate google analytics
# google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
